### ISSUE TITLE
marked lexer error

### ISSUE THREAD

**Issue by terietor** [chjj/marked#146]
Hello,

I tried today the marked 0.2.8 and it failed

this is the error

```
Please report this to https://github.com/chjj/marked.
    at Lexer.lex (/home/tsiapaliokas/src/kdesrc/kdereview/bodega-server/server/node_modules/marked/lib/marked.js:130:6)
    at Function.Lexer.lex (/home/tsiapaliokas/src/kdesrc/kdereview/bodega-server/server/node_modules/marked/lib/marked.js:121:16)
    at marked (/home/tsiapaliokas/src/kdesrc/kdereview/bodega-server/server/node_modules/marked/lib/marked.js:1017:31)
    at /home/tsiapaliokas/src/kdesrc/kdereview/bodega-server/server/routes.js:273:22
    at fs.js:252:14
    at Object.oncomplete (fs.js:93:15)
```

**Comment by joshbruce** [comment]
Closing as stale.
