### ISSUE TITLE
TypeError: Cannot call method 'replace' of null

### ISSUE THREAD

**Issue by Rowno** [chjj/marked#417]
```
TypeError: Cannot call method 'replace' of null 
Please report this to https://github.com/chjj/marked. 
at Lexer.lex (/app/node_modules/marked/lib/marked.js:137:6) 
at Function.Lexer.lex (/app/node_modules/marked/lib/marked.js:128:16) 
at marked (/app/node_modules/marked/lib/marked.js:1201:31) 
at Object.PullRequestEvent (/app/lib/events.js:257:20) 
at /app/lib/events.js:41:42 
at Promise.apply (/app/node_modules/q/q.js:1120:26) 
at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:751:41) 
at /app/node_modules/q/q.js:1335:14 
at flush (/app/node_modules/q/q.js:108:17) 
at /app/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:177:31 
```

**Comment by bnvk** [comment]
Yup! Just encountered this issue in a lil tool that uses `marked`

```
/home/user/Tools/offline-issues/node_modules/marked/lib/marked.js:1226
    throw e;
    ^

TypeError: Cannot read property 'replace' of null
Please report this to https://github.com/chjj/marked.
    at Lexer.lex (/home/user/Tools/offline-issues/node_modules/marked/lib/marked.js:138:5)
    at Function.Lexer.lex (/home/user/Tools/offline-issues/node_modules/marked/lib/marked.js:129:16)
    at marked (/home/user/Tools/offline-issues/node_modules/marked/lib/marked.js:1218:31)
    at parseBody (/home/user/Tools/offline-issues/src/writehtml.js:58:16)
    at /home/user/Tools/offline-issues/src/writehtml.js:35:13
    at Array.forEach (native)
    at writehtml (/home/user/Tools/offline-issues/src/writehtml.js:34:10)
    at /home/user/Tools/offline-issues/src/index.js:132:7
    at /home/user/Tools/offline-issues/node_modules/cpr/node_modules/rimraf/node_modules/graceful-fs/graceful-fs.js:90:5
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by joshbruce** [comment]
Working toward resolution - closing to clean up issues.
