### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by benjamingr** [chjj/marked#614]
Being a good citizen.

```
TypeError: undefined is not a function
Please report this to https://github.com/chjj/marked.
    at Lexer.lex (/Users/Benjamin/Desktop/testFiddle/node_modules/marked/lib/marked.js:137:6)
    at Function.Lexer.lex (/Users/Benjamin/Desktop/testFiddle/node_modules/marked/lib/marked.js:128:16)
    at marked (/Users/Benjamin/Desktop/testFiddle/node_modules/marked/lib/marked.js:1207:31)
    at /Users/Benjamin/Desktop/testFiddle/index.js:17:9
    at Layer.handle [as handle_request] (/Users/Benjamin/Desktop/testFiddle/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/Benjamin/Desktop/testFiddle/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/Benjamin/Desktop/testFiddle/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/Benjamin/Desktop/testFiddle/node_modules/express/lib/router/layer.js:95:5)
    at /Users/Benjamin/Desktop/testFiddle/node_modules/express/lib/router/index.js:277:22
    at param (/Users/Benjamin/Desktop/testFiddle/node_modules/express/lib/router/index.js:349:14)
```

**Comment by benjamingr** [comment]
Oh lol, silly me - forgot to add what triggered it.

This was caused because I passed a buffer instead of a String to marked. Passing a string fixed it.

**Comment by codeshrew** [comment]
:+1: 

This same thing confused me too. Thanks for the fix/usage-note @benjamingr

**Comment by DelvarWorld** [comment]
:+1: just bit me - needs obvious error for when a non-string is passed in

**Comment by SN4T14** [comment]
:+1: Just had this issue as well, very annoying.

**Comment by Feder1co5oave** [comment]
Solved. @joshbruce
