### ISSUE TITLE
robotskirt is no longer supported and breaking?

### ISSUE THREAD

**Issue by brianllamar** [chjj/marked#633]
When I forked the repo and ran `npm install` I get the below error. I [opened an issue](https://github.com/benmills/robotskirt/issues/36) on the roboskirt repo and got a response recommending using hoedown. 

Do you get the same error? And/Or have a work around?

I am running node v0.12.0, not sure if that is an issue? 

```
In file included from ../src/robotskirt.cc:1:
../src/v8u.hpp:85:43: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
inline void CheckArguments(int min, const v8::Arguments& args) {
                                          ^~~~~~~~~~~~~
                                          v8::internal::Arguments
/Users/bdoug/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/robotskirt.cc:1:
../src/v8u.hpp:86:11: error: member access into incomplete type 'const v8::internal::Arguments'
  if (args.Length() < min)
          ^
/Users/bdoug/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
In file included from ../src/robotskirt.cc:1:
../src/v8u.hpp:87:38: error: 'New' is a private member of 'v8::PersistentBase<v8::Value>'
    throw v8::Persistent<v8::Value>::New(v8::Exception::RangeError(v8::String::New("Not enough arguments.")));
                                     ^
/Users/bdoug/.node-gyp/0.12.0/deps/v8/include/v8.h:572:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
In file included from ../src/robotskirt.cc:1:
../src/v8u.hpp:87:80: error: no member named 'New' in 'v8::String'
    throw v8::Persistent<v8::Value>::New(v8::Exception::RangeError(v8::String::New("Not enough arguments.")));
                                                                   ~~~~~~~~~~~~^
../src/v8u.hpp:187:37: error: 'New' is a private member of 'v8::PersistentBase<v8::Value>'
  return v8::Persistent<v8::Value>::New(handle);
                                    ^
/Users/bdoug/.node-gyp/0.12.0/deps/v8/include/v8.h:572:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
In file included from ../src/robotskirt.cc:1:
../src/v8u.hpp:187:47: error: too few arguments to function call, expected 2, have 1
  return v8::Persistent<v8::Value>::New(handle);
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~       ^
/Users/bdoug/.node-gyp/0.12.0/deps/v8/include/v8.h:572:3: note: 'New' declared here
  V8_INLINE static T* New(Isolate* isolate, T* that);
  ^
/Users/bdoug/.node-gyp/0.12.0/deps/v8/include/v8config.h:289:20: note: expanded from macro 'V8_INLINE'
# define V8_INLINE inline __attribute__((always_inline))
                   ^
In file included from ../src/robotskirt.cc:1:
../src/v8u.hpp:225:34: error: too few arguments to function call, expected 2, have 1
  return v8::Integer::New(integer);
         ~~~~~~~~~~~~~~~~        ^
/Users/bdoug/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:3: note: 'New' declared here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
In file included from ../src/robotskirt.cc:1:
../src/v8u.hpp:229:46: error: too few arguments to function call, expected 2, have 1
  return v8::Integer::NewFromUnsigned(integer);
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~        ^
/Users/bdoug/.node-gyp/0.12.0/deps/v8/include/v8.h:2013:3: note: 'NewFromUnsigned' declared here
  static Local<Integer> NewFromUnsigned(Isolate* isolate, uint32_t value);
  ^
In file included from ../src/robotskirt.cc:1:
../src/v8u.hpp:233:22: error: no member named 'New' in 'v8::String'
  return v8::String::New(data);
         ~~~~~~~~~~~~^
../src/v8u.hpp:237:22: error: no member named 'New' in 'v8::String'
  return v8::String::New(str.data(), str.length());
         ~~~~~~~~~~~~^
../src/v8u.hpp:241:22: error: no member named 'NewSymbol' in 'v8::String'
  return v8::String::NewSymbol(data);
         ~~~~~~~~~~~~^
../src/v8u.hpp:245:26: error: too few arguments to function call, single argument 'isolate' was not specified
  return v8::Object::New();
         ~~~~~~~~~~~~~~~ ^
/Users/bdoug/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:3: note: 'New' declared here
  static Local<Object> New(Isolate* isolate);
  ^
In file included from ../src/robotskirt.cc:1:
../src/v8u.hpp:253:1: error: no member named 'New' in 'v8::String'
__V8_ERROR_CTOR()
^~~~~~~~~~~~~~~~~
../src/v8u.hpp:250:50: note: expanded from macro '__V8_ERROR_CTOR'
  return v8::Exception::ERROR##Error(v8::String::New(msg));                    \
                                     ~~~~~~~~~~~~^
../src/v8u.hpp:254:1: error: no member named 'New' in 'v8::String'
__V8_ERROR_CTOR(Range)
^~~~~~~~~~~~~~~~~~~~~~
../src/v8u.hpp:250:50: note: expanded from macro '__V8_ERROR_CTOR'
  return v8::Exception::ERROR##Error(v8::String::New(msg));                    \
                                     ~~~~~~~~~~~~^
../src/v8u.hpp:255:1: error: no member named 'New' in 'v8::String'
__V8_ERROR_CTOR(Reference)
^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/v8u.hpp:250:50: note: expanded from macro '__V8_ERROR_CTOR'
  return v8::Exception::ERROR##Error(v8::String::New(msg));                    \
                                     ~~~~~~~~~~~~^
../src/v8u.hpp:256:1: error: no member named 'New' in 'v8::String'
__V8_ERROR_CTOR(Syntax)
^~~~~~~~~~~~~~~~~~~~~~~
../src/v8u.hpp:250:50: note: expanded from macro '__V8_ERROR_CTOR'
  return v8::Exception::ERROR##Error(v8::String::New(msg));                    \
                                     ~~~~~~~~~~~~^
../src/v8u.hpp:257:1: error: no member named 'New' in 'v8::String'
__V8_ERROR_CTOR(Type)
^~~~~~~~~~~~~~~~~~~~~
../src/v8u.hpp:250:50: note: expanded from macro '__V8_ERROR_CTOR'
  return v8::Exception::ERROR##Error(v8::String::New(msg));                    \
                                     ~~~~~~~~~~~~^
../src/v8u.hpp:260:32: error: too few arguments to function call, expected 2, have 1
  return v8::Number::New(number);
         ~~~~~~~~~~~~~~~       ^
/Users/bdoug/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:3: note: 'New' declared here
  static Local<Number> New(Isolate* isolate, double value);
  ^
In file included from ../src/robotskirt.cc:1:
../src/v8u.hpp:264:34: error: too few arguments to function call, expected 2, have 1
  return v8::Boolean::New(boolean);
         ~~~~~~~~~~~~~~~~        ^
/Users/bdoug/.node-gyp/0.12.0/deps/v8/include/v8.h:6194:1: note: 'New' declared here
Handle<Boolean> Boolean::New(Isolate* isolate, bool value) {
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/robotskirt/src/robotskirt.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/bdoug/Desktop/marked/node_modules/robotskirt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! robotskirt@2.7.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robotskirt@2.7.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the robotskirt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls robotskirt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bdoug/Desktop/marked/npm-debug.log
```

**Comment by chjj** [comment]
It looks like robotskirt doesn't use nan.h now that were in an era of a new v8 api. I'll remove it from the devDependencies for now.
