### ISSUE TITLE
Error while generating HTML, the markdown is dumped followed by 'has no method replace'

### ISSUE THREAD

**Issue by ahmedabadawi** [chjj/marked#658]
has no method 'replace'
Please report this to https://github.com/chjj/marked.
    at Lexer.lex (/home/abadawi/work/playground/playground-node/markdown-server/node_modules/marked/lib/marked.js:138:6)
    at Function.Lexer.lex (/home/abadawi/work/playground/playground-node/markdown-server/node_modules/marked/lib/marked.js:129:16)
    at marked (/home/abadawi/work/playground/playground-node/markdown-server/node_modules/marked/lib/marked.js:1218:31)
    at /home/abadawi/work/playground/playground-node/markdown-server/server.js:18:19
    at fs.js:268:14
    at Object.oncomplete (fs.js:107:15)

**Comment by libchaos** [comment]
Did you solev it ?

**Comment by Feder1co5oave** [comment]
https://github.com/chjj/marked/issues/678#issuecomment-156841629

**Comment by joshbruce** [comment]
Closing as resolved...though @Feder1co5oave - we will not merge PRs without tests demonstrating the use case and passing case.
