### ISSUE TITLE
src.replace is not a function

### ISSUE THREAD

**Issue by Larry850806** [chjj/marked#755]
TypeError: src.replace is not a function
Please report this to https://github.com/chjj/marked.
    at Lexer.lex (/Users/larry/Desktop/repos/CoolSlide/cool-slide/node_modules/marked/lib/marked.js:138:6)
    at Function.Lexer.lex (/Users/larry/Desktop/repos/CoolSlide/cool-slide/node_modules/marked/lib/marked.js:129:16)
    at marked (/Users/larry/Desktop/repos/CoolSlide/cool-slide/node_modules/marked/lib/marked.js:1218:31)

**Comment by twoenzo** [comment]
+1

**Comment by uiteoi** [comment]
Make sure that the first parameter to marked() is a string.

Returning null or throwing a custom exception would help diagnose this issue.
