### ISSUE TITLE
Using esdoc, please report to  ...

### ISSUE THREAD

**Issue by iffy** [chjj/marked#851]
I just installed `esdoc` and ran it and got this error:

```
TypeError: Cannot read property '1' of null
Please report this to https://github.com/chjj/marked.
    at Object.sanitizer (/Users/matt/m/lhtml/node_modules/esdoc/out/src/Publisher/Builder/util.js:89:46)
    at InlineLexer.output (/Users/matt/m/lhtml/node_modules/marked/lib/marked.js:612:26)
    at Parser.tok (/Users/matt/m/lhtml/node_modules/marked/lib/marked.js:1075:50)
    at Parser.parse (/Users/matt/m/lhtml/node_modules/marked/lib/marked.js:935:17)
    at Function.Parser.parse (/Users/matt/m/lhtml/node_modules/marked/lib/marked.js:922:17)
    at marked (/Users/matt/m/lhtml/node_modules/marked/lib/marked.js:1219:19)
    at markdown (/Users/matt/m/lhtml/node_modules/esdoc/out/src/Publisher/Builder/util.js:80:41)
    at IndexDocBuilder._buildIndexDoc (/Users/matt/m/lhtml/node_modules/esdoc/out/src/Publisher/Builder/IndexDocBuilder.js:73:44)
    at IndexDocBuilder.exec (/Users/matt/m/lhtml/node_modules/esdoc/out/src/Publisher/Builder/IndexDocBuilder.js:49:30)
    at publish (/Users/matt/m/lhtml/node_modules/esdoc/out/src/Publisher/publish.js:146:58)
```

So... I did what I was told.  I'm happy to help debug.

**Comment by Feder1co5oave** [comment]
The error happened outside of marked (i.e. in util.js)
